### ISSUE TITLE
Laravel 5.8

### ISSUE THREAD

**Issue by EgorGruzdev** [dogadogmbh/baum#8]
https://github.com/dogadogmbh/baum/blob/69bbcd94e0ce82cd2124708bf79c167e9a8793d6/src/Move.php#L398

The fire Method
Likelihood Of Impact: Low

The fire method (which was deprecated in Laravel 5.4) of the Illuminate/Events/Dispatcher class has been removed. You should use the dispatch method instead.

**Comment by darthsoup** [comment]
fixed
